
apiVersion: v1

kind: Service

metadata:

  name: myapp-deployment

spec:

  type: NodePort

  selector:

    app: myapp-deployment

  ports:

  - protocol: TCP

    port: 8000

    targetPort: 8000

